app:
  debug: true
  port: 5000
  host: 127.0.0.1

scheduler:
  data_crawl:
    interval: 900 # seconds
  data_train:
    interval: 600

data:
  base_path : './data/'

model:
  name: 'ollama-deepseek-8b-bge-m3'
  configuration:
    ollama-mistral-nomic-embed-text:
      chunk_size: 300
      chunk_overlap: 100
    ollama-deepseek-8b-nomic-embed-text:
      chunk_size: 300
      chunk_overlap: 100
    ollama-deepseek-8b-bge-m3:
      chunk_size: 300
      chunk_overlap: 100
    openai-similarity-search-model:
      openai:
        key: '{{OPEN_AI_KEY_PLACEHOLDER}}'
      ranking-groups: 3



